# Generated by Django 2.1 on 2020-08-31 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20180915_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
